name = "ananas-app" # You can change this to a unique name for your application
compatibility_date = "2024-07-29" # Using a recent compatibility date

[site]
bucket = "./dist" # This tells Wrangler to deploy the contents of your 'dist' folder as static assets